name = "FreeRay"
uuid = "3c5c1728-634c-4091-8bcd-fe4b17a439e3"
authors = ["Duc-Phuc Nguyen"]
version = "0.1.0"

[deps]
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
